### ISSUE TITLE
How to fix Greenwald fraction

### ISSUE THREAD

**Issue by qwerty2684** [cfs-energy/cfspopcon#76]
In the example, the average density and temperature is scanned, and the Greenwald fraction is obtained after a set of calculations. Now, I want to scan temperature and current with average density fixed to a given Greenwald fraction, e.g., ne_avg=0.4n_GW. How can I set the fixed Greenwald fraction?

**Comment by tbody-cfs** [comment]
Hi @qwerty2684,

I've just opened #77 which shows how you can set a fixed Greenwald fraction and compute the average electron density. If you switch to that branch or wait until it is merged into main, you should be able to do something like the following

```yaml
algorithms:
  - read_atomic_data
  - calc_separatrix_elongation_from_areal_elongation
  - calc_separatrix_triangularity_from_triangularity95
  - calc_minor_radius_from_inverse_aspect_ratio
  - calc_vertical_minor_radius_from_elongation_and_minor_radius
  - calc_plasma_volume
  - calc_plasma_surface_area
  - calc_f_shaping_for_qstar
  - calc_q_star_from_plasma_current
  - calc_greenwald_density_limit
  - calc_average_electron_density_from_greenwald_fraction
  - calc_average_fuel_ion_mass
  - calc_average_ion_temp_from_temperature_ratio
  - calc_zeff_and_dilution_due_to_impurities
  - calc_plasma_stored_energy
  - read_confinement_scalings
  - solve_tau_e_scaling_for_input_power

grid:
  # input variables in the 'grid' block will be replaced by
  # a corresponding linspace or logspace of values

  plasma_current:
    # Plasma current in A
    min: 0.1e+6
    max: 10.0e+6
    num: 40
    spacing: log

  average_electron_temp:
    # Average electron temperature in keV
    min: 5.0
    max: 20.0
    num: 30
    spacing: linear

# Toroidal field on-axis in Tesla
magnetic_field_on_axis: 12.2
# Major radius in metres
major_radius: 1.85
# Inverse aspect ratio
inverse_aspect_ratio: 0.3081
# Areal elongation
areal_elongation: 1.75
# Ratio of separatrix_elongation to kappa_A
elongation_ratio_sep_to_areal: 1.125
# Triangularity at rho_pol = 0.95
triangularity_psi95: 0.3
# Ratio of separatrix_triangularity to delta_95
triangularity_ratio_sep_to_psi95: 1.8
# Fixed Greenwald fraction
greenwald_fraction: 0.4
# Ratio of volume-averaged temperatures (Ti / Te)
ion_to_electron_temp_ratio: 1.0

# What fusion reaction are we using?
fusion_reaction: DTFusionHively
# Fraction of fuel ions which are the heavier species
heavier_fuel_species_fraction: 0.5

# Confinement enhancement factor
confinement_time_scalar: 1.0
# Name of the tau_e scaling used
tau_e_scaling: ITER98y2

radas_dir: "WORKING_DIR/radas_dir"

impurities:
  # Impurity concentration relative to electron density.
  Tungsten: 1.5e-5
  Helium: 6.0e-2
  Oxygen: 3.1e-3
```
